In [1]:
from _element import feature_control as ftc

In [2]:
import pandas as pd

In [3]:
from datetime import datetime

In [4]:
df= pd.ExcelFile('.\\_element\\data\\private\\KPP일별투입(10_17).xlsx')

In [5]:
df.sheet_names

['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017']

In [6]:
df_txs= pd.DataFrame(columns= ['구분','타입','코드','발송일','유형','수량'])

In [7]:
type(df_txs)

pandas.core.frame.DataFrame

In [8]:
for sheet_name in df.sheet_names:
    df_sheet= df.parse(sheet_name)
    df_txs= pd.concat([df_txs, df_sheet])

In [9]:
df_txs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1300503 entries, 0 to 189668
Data columns (total 6 columns):
구분     1300503 non-null object
타입     1300503 non-null object
코드     1300503 non-null object
발송일    1300503 non-null object
유형     1300503 non-null object
수량     1300503 non-null object
dtypes: object(6)
memory usage: 69.5+ MB

In [10]:
date_change= lambda x: datetime(int(x[:4]),int(x[4:6]),int(x[6:])) if len(x)==8 \
                            else datetime.strptime(x, "%Y-%m-%d")

In [11]:
df= df_txs

In [12]:
df['발송일']=df['발송일'].map(str).map(date_change)
df= df.groupby([df['발송일'], df['유형']])['수량'].sum().unstack('유형')
df.fillna(0, inplace= True)
df['y_sum']= df.sum(axis=1)

In [13]:
df.head(30)

유형,1025,1041,1057,1091,1111,1117,1119,1127,1163,1216,...,1754,1797,1800,1815,1817,1852,1853,1878,1891,y_sum
발송일,,,,,,,,,,,,,,,,,,,,,
2010-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2652.0,0.0,0.0,0.0,0.0,0.0,2662.0
2010-01-02,192.0,6260.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,337.0,0.0,0.0,26443.0,0.0,0.0,459.0,626.0,0.0,39352.0
2010-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,404.0,0.0,0.0,0.0,0.0,0.0,404.0
2010-01-04,0.0,5141.0,0.0,320.0,0.0,0.0,0.0,0.0,0.0,0.0,...,154.0,576.0,0.0,22924.0,0.0,0.0,3445.0,3305.0,0.0,44906.0
2010-01-05,130.0,5494.0,0.0,1186.0,0.0,0.0,0.0,0.0,0.0,16.0,...,367.0,294.0,0.0,39081.0,320.0,0.0,3861.0,4362.0,238.0,69481.0
2010-01-06,9.0,10300.0,0.0,957.0,0.0,0.0,0.0,0.0,0.0,20.0,...,442.0,239.0,10.0,41411.0,0.0,0.0,3353.0,6643.0,480.0,78393.0
2010-01-07,368.0,11193.0,0.0,736.0,0.0,0.0,0.0,0.0,0.0,0.0,...,490.0,442.0,0.0,42029.0,0.0,0.0,4317.0,3718.0,144.0,81525.0
2010-01-08,60.0,12480.0,0.0,494.0,0.0,0.0,0.0,0.0,0.0,280.0,...,157.0,1164.0,0.0,45205.0,0.0,0.0,5338.0,6258.0,0.0,89583.0
2010-01-09,0.0,4117.0,0.0,224.0,0.0,0.0,0.0,0.0,0.0,0.0,...,190.0,80.0,0.0,31304.0,0.0,0.0,3463.0,3219.0,0.0,51709.0
2010-01-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,336.0,0.0,0.0,0.0,0.0,0.0,336.0
2010-01-11,211.0,6268.0,0.0,266.0,0.0,0.0,0.0,60.0,0.0,170.0,...,187.0,760.0,39.0,42702.0,300.0,0.0,4805.0,4328.0,364.0,76448.0
2010-01-12,63.0,4820.0,0.0,460.0,0.0,0.0,0.0,140.0,0.0,50.0,...,606.0,64.0,12.0,46035.0,0.0,0.0,4994.0,5702.0,348.0,80079.0
2010-01-13,315.0,6615.0,0.0,416.0,0.0,0.0,0.0,37.0,0.0,48.0,...,835.0,857.0,92.0,40989.0,0.0,0.0,3642.0,4186.0,144.0,74026.0
2010-01-14,0.0,6677.0,0.0,308.0,0.0,0.0,0.0,0.0,0.0,0.0,...,298.0,822.0,0.0,40006.0,0.0,0.0,4333.0,4463.0,906.0,74894.0
2010-01-15,130.0,7215.0,0.0,740.0,0.0,0.0,0.0,120.0,0.0,0.0,...,343.0,1577.0,0.0,44257.0,0.0,0.0,4338.0,5505.0,792.0,80818.0
2010-01-16,0.0,4514.0,0.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,...,377.0,2322.0,0.0,29985.0,0.0,0.0,5260.0,1770.0,0.0,54602.0
2010-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,568.0,0.0,0.0,0.0,0.0,0.0,568.0
2010-01-18,40.0,3975.0,0.0,320.0,0.0,0.0,0.0,0.0,0.0,0.0,...,158.0,778.0,0.0,44099.0,0.0,0.0,4825.0,4119.0,464.0,75083.0
2010-01-19,51.0,6918.0,0.0,388.0,0.0,0.0,0.0,0.0,0.0,0.0,...,405.0,0.0,0.0,42713.0,320.0,0.0,4698.0,5569.0,320.0,76767.0
2010-01-20,245.0,3567.0,0.0,224.0,0.0,0.0,0.0,0.0,0.0,69.0,...,756.0,161.0,0.0,40365.0,0.0,0.0,5217.0,3824.0,144.0,71655.0
2010-01-21,252.0,4758.0,0.0,32.0,0.0,0.0,0.0,100.0,0.0,546.0,...,368.0,1379.0,0.0,34943.0,0.0,0.0,4728.0,5163.0,0.0,69342.0
2010-01-22,360.0,3970.0,0.0,414.0,0.0,0.0,0.0,0.0,0.0,214.0,...,375.0,720.0,30.0,37524.0,0.0,0.0,4636.0,6225.0,144.0,71053.0
2010-01-23,0.0,4852.0,0.0,128.0,0.0,0.0,0.0,0.0,0.0,48.0,...,405.0,538.0,0.0,29112.0,0.0,0.0,3410.0,1806.0,758.0,48681.0
2010-01-24,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1500.0,0.0,0.0,400.0,192.0,0.0,2192.0
2010-01-25,144.0,6644.0,0.0,488.0,0.0,0.0,0.0,137.0,0.0,0.0,...,307.0,632.0,0.0,38761.0,0.0,0.0,4404.0,3256.0,0.0,68989.0
2010-01-26,158.0,6499.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,90.0,...,517.0,1319.0,0.0,47845.0,0.0,0.0,5532.0,5042.0,0.0,83813.0
2010-01-27,361.0,3928.0,0.0,352.0,0.0,0.0,0.0,0.0,0.0,165.0,...,325.0,2116.0,0.0,37623.0,0.0,0.0,5300.0,5597.0,170.0,73299.0
2010-01-28,60.0,5275.0,0.0,457.0,0.0,0.0,0.0,0.0,0.0,20.0,...,281.0,633.0,10.0,33242.0,0.0,0.0,5536.0,3647.0,348.0,66113.0
2010-01-29,688.0,6010.0,0.0,576.0,0.0,0.0,0.0,66.0,0.0,144.0,...,351.0,857.0,36.0,34553.0,0.0,0.0,5734.0,3721.0,396.0,69556.0
2010-01-30,11.0,5134.0,0.0,160.0,0.0,0.0,0.0,0.0,0.0,1.0,...,144.0,586.0,0.0,32310.0,0.0,0.0,4144.0,3632.0,430.0,54167.0

In [14]:
df.tail(10)

유형,1025,1041,1057,1091,1111,1117,1119,1127,1163,1216,...,1754,1797,1800,1815,1817,1852,1853,1878,1891,y_sum
발송일,,,,,,,,,,,,,,,,,,,,,
2017-11-21,114.0,6710.0,704.0,485.0,0.0,0.0,1088.0,0.0,0.0,0.0,...,410.0,0.0,0.0,72977.0,0.0,0.0,5715.0,7296.0,0.0,121680.0
2017-11-22,28.0,6727.0,666.0,224.0,0.0,0.0,1088.0,0.0,0.0,0.0,...,720.0,0.0,0.0,77506.0,0.0,0.0,5366.0,4754.0,0.0,122640.0
2017-11-23,0.0,7964.0,326.0,0.0,0.0,0.0,448.0,0.0,0.0,0.0,...,240.0,46.0,0.0,71739.0,0.0,0.0,5154.0,4123.0,0.0,110220.0
2017-11-24,0.0,8733.0,272.0,640.0,0.0,0.0,576.0,0.0,0.0,0.0,...,610.0,0.0,0.0,70495.0,0.0,0.0,5928.0,7409.0,0.0,120647.0
2017-11-25,0.0,5100.0,181.0,224.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,43952.0,0.0,0.0,1885.0,2604.0,0.0,67756.0
2017-11-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,100.0
2017-11-27,0.0,4866.0,489.0,448.0,0.0,0.0,416.0,0.0,0.0,0.0,...,480.0,0.0,0.0,75686.0,224.0,0.0,5417.0,5513.0,0.0,117480.0
2017-11-28,0.0,5723.0,846.0,0.0,0.0,0.0,633.0,0.0,0.0,0.0,...,750.0,0.0,0.0,77009.0,224.0,0.0,7159.0,6178.0,0.0,122192.0
2017-11-29,0.0,6732.0,0.0,416.0,0.0,0.0,990.0,0.0,0.0,0.0,...,670.0,0.0,0.0,77341.0,224.0,0.0,4847.0,5062.0,0.0,120685.0
2017-11-30,0.0,6909.0,254.0,596.0,0.0,0.0,160.0,0.0,0.0,0.0,...,0.0,18.0,0.0,68600.0,0.0,0.0,5586.0,4166.0,0.0,108386.0

In [17]:
df= ftc.dir_walk('.\\_element\\data\\temp_data', df)

.\_element\data\temp_data\2010_rain.csv

TypeError: set_axis() got multiple values for argument 'axis'